services:
   reverse-proxy:
      restart: unless-stopped
      image: caddy:latest
      volumes:
         - ./Caddyfile:/etc/caddy/Caddyfile
      ports:
         - 3000:3000
   frontend:
      restart: unless-stopped
      build:
         context: frontend
         dockerfile: Dockerfile.local
      environment:
         - BACKEND_URL=http://backend:3000
      volumes:
         - ./frontend:/frontend
         - /frontend/node_modules
   backend:
      restart: unless-stopped
      build:
         context: backend
         dockerfile: Dockerfile.local
      volumes:
         - ./backend:/backend
         - /backend/node_modules
